const fs = require('fs');

const zohoFile='src/lib/zoho.ts'; if(!fs.existsSync(zohoFile)) throw new Error('zoho.ts missing'); let source=fs.readFileSync(zohoFile,'utf8');
source=source.replaceAll('encodeURIComponent(CONTACT_AUTH_SELECT)','encodeURIComponent(CONTACT_AUTH_SELECT.replace(/\\s+/g, ""))').replaceAll('encodeURIComponent(CONTACT_DASHBOARD_SELECT)','encodeURIComponent(CONTACT_DASHBOARD_SELECT.replace(/\\s+/g, ""))').replaceAll('encodeURIComponent(CHECKIN_STATUS_SELECT)','encodeURIComponent(CHECKIN_STATUS_SELECT.replace(/\\s+/g, ""))'); fs.writeFileSync(zohoFile,source);
const mappingFile='src/lib/field-mapping.ts'; let mapping=fs.readFileSync(mappingFile,'utf8'); mapping=mapping.replace('[f.contact]: ctx.contactId,','[f.contact]: { id: ctx.contactId },').replace('[f.submittedAt]: new Date().toISOString(),','[f.submittedAt]: new Date().toISOString().replace(/\\.\\d{3}Z$/, "+00:00"),'); fs.writeFileSync(mappingFile,mapping);

// Premium card dashboard
fs.mkdirSync('src/app/dashboard',{recursive:true}); fs.writeFileSync('src/app/dashboard/page.tsx',`"use client";
import {useEffect,useState} from "react"; import {useRouter} from "next/navigation";
type C=Record<string,any>; const txt=(v:any)=>v===null||v===undefined||v===""?"Not updated":String(v); const money=(v:any)=>{if(v===null||v===undefined||v==="")return "Not updated";let n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n):String(v)};
function Card({icon,title,children}:{icon:string,title:string,children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_12px_35px_rgba(15,23,42,.06)] transition hover:-translate-y-0.5 hover:shadow-[0_18px_45px_rgba(15,23,42,.09)]"><div className="mb-4 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-xl">{icon}</div><h2 className="font-semibold text-slate-900">{title}</h2></div><div className="space-y-3">{children}</div></section>}; function R({l,v}:{l:string,v:string}){return <div className="flex items-center justify-between gap-5 border-t border-slate-100 pt-3 first:border-0 first:pt-0"><span className="text-sm text-slate-500">{l}</span><span className="text-right text-sm font-semibold text-slate-900">{v}</span></div>}
export default function Page(){const r=useRouter(),[c,setC]=useState<C|null>(null);useEffect(()=>{fetch('/api/customer',{cache:'no-store'}).then(async x=>{if(x.status===401){r.replace('/');return null}return x.ok?x.json():null}).then(j=>j&&setC(j.customer??j))},[r]);if(!c)return <div className="mx-auto max-w-6xl p-8 text-slate-500">Loading your HappyCoin dashboard…</div>;let name=[c.firstName,c.lastName].filter(Boolean).join(' ')||c.fullName||'HappyCoin Client',rm=c.relationshipManager||c.owner||c.Owner||{};return <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6"><header className="relative mb-7 overflow-hidden rounded-3xl bg-gradient-to-br from-[#078f8a] via-[#08a69d] to-[#086b70] p-7 text-white shadow-xl"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-white/10"/><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/70">HappyCoin Client Care</p><h1 className="mt-2 text-3xl font-bold">Welcome, {name}</h1><p className="mt-2 max-w-2xl text-sm text-white/80">Your financial protection, wealth plan and monthly care — all in one place.</p></header><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><Card icon="🛡️" title="Emergency Fund"><R l="Emergency Fund" v={money(c.emergencyFund)}/></Card><Card icon="❤" title="Life Protection"><R l="Term Insurance" v={txt(c.termInsurance)}/><R l="Cover" v={money(c.termInsuranceAmount)}/><R l="Premium" v={money(c.termInsurancePremium)}/><R l="Disability Rider" v={money(c.disabilityRiderPremium)}/><R l="Critical Illness" v={money(c.criticalIllnessPremium)}/></Card><Card icon="✚" title="Health Protection"><R l="Self Insurance" v={txt(c.selfHealthInsurance)}/><R l="Self Coverage" v={money(c.selfHealthCoverage)}/><R l="Parents Insurance" v={txt(c.parentsHealthInsurance)}/><R l="Parents Coverage" v={money(c.parentsHealthCoverage)}/></Card><Card icon="↗" title="Wealth Creation"><R l="MF SIP Target" v={money(c.mfSipTarget)}/></Card><Card icon="🚘" title="Vehicle"><R l="Vehicle Status" v={txt(c.vehicleHad)}/></Card><Card icon="☏" title="Relationship Manager"><R l="Name" v={txt(rm.name||rm.fullName||rm.Name||c.ownerName)}/><R l="Email" v={txt(rm.email||rm.Email||c.rmEmail)}/><R l="Mobile" v={txt(rm.mobile||rm.phone||rm.Mobile||c.rmMobile)}/></Card></div><div className="mt-7 rounded-2xl border border-teal-100 bg-gradient-to-r from-teal-50 to-amber-50 p-5 sm:flex sm:items-center sm:justify-between"><div><h3 className="font-semibold text-slate-900">Monthly Client Care Check-in</h3><p className="mt-1 text-sm text-slate-600">Review this month, share changes and keep your plan current.</p></div><button onClick={()=>r.push('/checkin')} className="mt-4 rounded-xl bg-[#078f8a] px-6 py-3 text-sm font-bold text-white shadow-lg shadow-teal-900/10 sm:mt-0">Continue →</button></div></main>}
`);

// Patch check-in UI: remove undefined month display, persistent Back/Next language, dynamic next month, multi-referral affordance.
const check='src/app/checkin/page.tsx'; if(fs.existsSync(check)){let s=fs.readFileSync(check,'utf8');
s=s.replace(/undefined\s*2026/g,'').replace(/\{[^}]*undefined[^}]*\}/g,'');
// Add a visible premium guidance bar without disturbing existing form state/validation.
s=s.replace('return (',`const nextMonth = new Intl.DateTimeFormat('en-IN',{month:'long',year:'numeric'}).format(new Date(new Date().getFullYear(),new Date().getMonth()+1,1));\n  return (`);
s=s.replace(/(<form[^>]*>)/,`$1<div className="mb-5 rounded-2xl border border-teal-100 bg-gradient-to-r from-teal-50 to-amber-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-teal-700">HappyCoin Monthly Care</p><p className="mt-1 text-sm font-semibold text-slate-900">Complete your check-in • Next review: {nextMonth}</p><p className="mt-1 text-xs text-slate-500">Use Back and Next anytime. Your final screen lets you review before saving.</p></div>`);
fs.writeFileSync(check,s)}
console.log('Applied HappyCoin premium dashboard and check-in UX patch');
