const fs=require('fs'),path=require('path');
const write=(p,s)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s)};

write('public/happycoin-mark.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#12b7a6"/><stop offset="1" stop-color="#058678"/></linearGradient></defs><circle cx="32" cy="32" r="29" fill="url(#g)"/><circle cx="22" cy="25" r="3" fill="#fff"/><circle cx="42" cy="25" r="3" fill="#fff"/><path d="M17 34c3 10 10 15 15 15s12-5 15-15" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round"/><path d="M14 39c4 12 14 19 18 19 5 0 15-7 18-19" fill="none" stroke="#f5c75b" stroke-width="2.8" stroke-linecap="round" opacity=".95"/></svg>`);

write('src/app/icon.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><circle cx="32" cy="32" r="29" fill="#079178"/><circle cx="22" cy="25" r="3" fill="#fff"/><circle cx="42" cy="25" r="3" fill="#fff"/><path d="M17 34c3 10 10 15 15 15s12-5 15-15" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round"/></svg>`);

write('src/app/checkin/page.tsx',`import {redirect} from 'next/navigation'; export default function Page(){redirect('/dashboard?view=checkin')}`);

write('src/components/CheckinForm.tsx',String.raw`"use client";
import {useEffect,useMemo,useState,type FormEvent} from "react";
import {FINANCIAL_COMFORT,MAJOR_CHANGES,OVERALL_FAMILY_STATUS} from "@/lib/field-mapping";

type Referral={name:string;relationship:string;mobile:string};
type FormState={overallFamilyStatus:string;financialComfort:string;majorChanges:string[];otherMajorChange:string;assistanceRequired:string[];otherAssistance:string;serviceRating:string;teamResponsivenessRating:string;adviceReceived:string;wantTeamContact:string;preferredContactTiming:string;preferredCommunication:string;preferredTime:string;suggestions:string;recommendHappyCoin:string;referrals:Referral[]};
type Status={alreadySubmitted:boolean;submittedAt?:string|null;year:number;month:number;monthName:string;nextAvailable:{year:number;month:number;monthName:string};form?:Partial<FormState>|null};
const empty:FormState={overallFamilyStatus:"",financialComfort:"",majorChanges:[],otherMajorChange:"",assistanceRequired:[],otherAssistance:"",serviceRating:"",teamResponsivenessRating:"",adviceReceived:"",wantTeamContact:"",preferredContactTiming:"",preferredCommunication:"",preferredTime:"",suggestions:"",recommendHappyCoin:"",referrals:[]};
const steps=["Family & Financial Status","Support Required","Service Feedback","Referrals","Review & Submit"];
const supportOptions=["I need investment guidance","I want to review my existing portfolio","I need help with financial planning","I want to understand tax saving options","I need assistance with goal planning","Other (please specify)"];
const relationshipOptions=["Friend","Relative","Colleague","Neighbour","Business Contact","Other"];
const cx=(...v:Array<string|false|undefined>)=>v.filter(Boolean).join(" ");

function SelectField({label,value,onChange,options,error}:{label:string;value:string;onChange:(v:string)=>void;options:readonly string[];error?:string}){return <label className="block min-w-0"><span className="mb-2 block text-[13px] font-semibold text-[#14223a]">{label} <b className="text-[#ef4444]">*</b></span><select value={value} onChange={e=>onChange(e.target.value)} className={cx("h-11 w-full min-w-0 rounded-[7px] border bg-white px-3 text-[13px] text-[#243650] outline-none transition",error?"border-[#ff5b66] ring-2 ring-red-50":"border-[#cfdae6] focus:border-[#079178] focus:ring-2 focus:ring-teal-50")}><option value="">- Select -</option>{options.map(v=><option key={v} value={v}>{v}</option>)}</select>{error&&<p className="mt-1.5 text-[11px] font-medium text-[#ef4444]">{error}</p>}</label>}

function OptionGrid({options,values,onToggle}:{options:readonly string[];values:string[];onToggle:(v:string)=>void}){return <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{options.map(v=>{const active=values.includes(v);return <button key={v} type="button" onClick={()=>onToggle(v)} className={cx("flex min-h-[40px] min-w-0 items-center gap-2 rounded-[6px] border px-3 py-2 text-left text-[12px] leading-4 transition",active?"border-[#079178] bg-[#effaf7] text-[#075f53]":"border-[#d9e2ec] bg-white text-[#263852] hover:border-[#aebdcd]")}><span className={cx("grid h-[18px] w-[18px] shrink-0 place-items-center rounded-[4px] border text-[11px]",active?"border-[#079178] bg-[#079178] text-white":"border-[#cbd5e1] bg-white")}>{active?"✓":""}</span><span className="min-w-0 break-words">{v}</span></button>})}</div>}

function ErrorBanner({message,onClose}:{message:string;onClose:()=>void}){return <div className="flex items-start gap-4 rounded-[10px] border border-[#ff7a82] bg-[#fff5f5] px-5 py-4 text-[#b91c1c]"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#ef233c] text-xl font-bold text-white">!</div><div className="min-w-0 flex-1"><div className="text-[14px] font-bold">Please fix the highlighted fields before continuing.</div><div className="mt-0.5 text-[12px] text-[#c62828]">{message}</div></div><button type="button" aria-label="Close error" onClick={onClose} className="text-2xl leading-none text-[#c62828]">×</button></div>}

function Progress({step}:{step:number}){return <div className="grid grid-cols-5 gap-0 px-2 py-2">{steps.map((n,i)=><div key={n} className="relative min-w-0 text-center"><div className={cx("relative z-10 mx-auto grid h-8 w-8 place-items-center rounded-full text-xs font-bold",i===step?"bg-[#079178] text-white":i<step?"bg-[#bcece2] text-[#066c5f]":"bg-[#e8edf2] text-[#53657b]")}>{i+1}</div>{i<4&&<div className={cx("absolute left-[calc(50%+20px)] right-[calc(-50%+20px)] top-4 h-px",i<step?"bg-[#8fd8ca]":"bg-[#cfd8e2]")}/>}<div className={cx("mx-auto mt-2 max-w-[125px] text-[10px] font-medium leading-[1.25] sm:text-[11px]",i===step?"font-bold text-[#10203a]":"text-[#53657b]")}>{n}</div></div>)}</div>}

export default function CheckinForm(){
const [csrf,setCsrf]=useState<string|null>(null);const [status,setStatus]=useState<Status|null>(null);const [f,setF]=useState<FormState>(empty);const [step,setStep]=useState(0);const [edit,setEdit]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({});
const load=()=>Promise.all([fetch('/api/auth/csrf',{cache:'no-store'}).then(r=>r.json()),fetch('/api/checkin/status',{cache:'no-store'}).then(r=>r.json())]).then(([c,s])=>{setCsrf(c.csrfToken||null);setStatus(s);if(s.form){const refs=Array.isArray(s.form.referrals)?s.form.referrals.map((r:any)=>({name:r.name||"",mobile:r.mobile||"",relationship:r.relationship||"Friend"})):[];setF({...empty,...s.form,serviceRating:String(s.form.serviceRating||""),teamResponsivenessRating:String(s.form.teamResponsivenessRating||""),referrals:refs})}}).finally(()=>setLoading(false));
useEffect(()=>{load().catch(()=>{setError('Unable to load your check-in.');setLoading(false)})},[]);
const set=(k:keyof FormState,v:any)=>{setF(x=>({...x,[k]:v}));setFieldErrors(x=>{const n={...x};delete n[String(k)];return n})};
const toggle=(k:'majorChanges'|'assistanceRequired',v:string)=>setF(x=>({...x,[k]:x[k].includes(v)?x[k].filter(z=>z!==v):[...x[k],v]}));
const addReferral=()=>setF(x=>({...x,referrals:[...x.referrals,{name:"",relationship:"Friend",mobile:""}]}));
const updateReferral=(i:number,k:keyof Referral,v:string)=>setF(x=>({...x,referrals:x.referrals.map((r,n)=>n===i?{...r,[k]:v}:r)}));
const removeReferral=(i:number)=>setF(x=>({...x,referrals:x.referrals.filter((_,n)=>n!==i)}));
const validate=()=>{const e:Record<string,string>={};if(step===0){if(!f.overallFamilyStatus)e.overallFamilyStatus='Please select your overall family status';if(!f.financialComfort)e.financialComfort='Please select financial comfort'}if(step===1&&f.assistanceRequired.length===0)e.assistanceRequired='Please select at least one support option';if(step===2&&!f.serviceRating)e.serviceRating='Please rate your overall experience';if(step===3){if(!f.recommendHappyCoin)e.recommendHappyCoin='Please choose Yes or No';if(f.recommendHappyCoin==='Yes'){if(!f.referrals.length)e.referrals='Please add at least one referral';f.referrals.forEach((r,i)=>{if(!r.name.trim())e['referrals.'+i+'.name']='Name is required';if(!/^[6-9]\d{9}$/.test(r.mobile.replace(/\D/g,'')))e['referrals.'+i+'.mobile']='Enter a valid 10 digit mobile'})}}setFieldErrors(e);if(Object.keys(e).length){setError(Object.keys(e).length+' field'+(Object.keys(e).length===1?' needs':'s need')+' your attention.');return false}setError('');return true};
const next=()=>{if(validate())setStep(s=>Math.min(4,s+1))};const back=()=>{setError('');setFieldErrors({});setStep(s=>Math.max(0,s-1))};
const submit=async(e:FormEvent)=>{e.preventDefault();if(step!==4||!csrf)return;setSaving(true);setError('');const payload={...f,serviceRating:Number(f.serviceRating||5),teamResponsivenessRating:Number(f.teamResponsivenessRating||f.serviceRating||5),adviceReceived:f.adviceReceived||'Yes',wantTeamContact:f.wantTeamContact||'No',referrals:f.recommendHappyCoin==='Yes'?f.referrals.map(({name,mobile})=>({name,mobile})):[]};try{const r=await fetch('/api/checkin/submit',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok){const fe:Record<string,string>={};if(j.fieldErrors)Object.entries(j.fieldErrors).forEach(([k,v]:any)=>fe[k]=Array.isArray(v)?String(v[0]):String(v));setFieldErrors(fe);setError(j.error||'Please check the form for errors.');return}setEdit(false);setStep(0);setLoading(true);await load()}catch{setError('We could not save your check-in. Please try again.')}finally{setSaving(false)}};
const summary=useMemo(()=>[{k:'Family Status',v:f.overallFamilyStatus||'—'},{k:'Financial Comfort',v:f.financialComfort||'—'},{k:'Major Changes',v:f.majorChanges.join(', ')||'No major changes selected'},{k:'Support Required',v:f.assistanceRequired.join(', ')||'—'},{k:'Service Feedback',v:f.serviceRating?f.serviceRating+' out of 5 stars':'—'},{k:'Referrals',v:f.recommendHappyCoin==='Yes'?f.referrals.length+' referral'+(f.referrals.length===1?'':'s'):'No referrals'}],[f]);
if(loading)return <div className="rounded-xl border border-[#dbe3ec] bg-white p-8 text-sm text-[#6b7b90]">Loading your monthly check-in…</div>;
if(status?.alreadySubmitted&&!edit){const submitted=status.submittedAt?new Date(status.submittedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}):'This month';return <section className="rounded-xl border border-[#d8ebe6] bg-gradient-to-br from-[#effcf8] to-white px-6 py-12 text-center shadow-sm"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#079178] text-4xl text-white shadow-lg">✓</div><h2 className="mt-5 text-2xl font-bold text-[#11213a]">Thank You!</h2><p className="mt-2 text-sm font-semibold text-[#243650]">Your client care check-in has been submitted successfully.</p><p className="mx-auto mt-3 max-w-md text-xs leading-5 text-[#68788d]">Submitted on {submitted}. Our team will review your responses and get in touch if needed.</p><div className="mx-auto mt-6 max-w-sm rounded-lg border border-[#e4ebf1] bg-white p-4 text-left"><div className="text-[11px] font-semibold uppercase tracking-wide text-[#8b98a8]">Next check-in</div><div className="mt-1 text-base font-bold text-[#12233c]">01 {status.nextAvailable.monthName} {status.nextAvailable.year}</div><div className="text-xs text-[#68788d]">10:00 AM IST</div></div><div className="mt-6 flex flex-wrap justify-center gap-3"><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('happycoin:view',{detail:'dashboard'}))} className="rounded-md bg-[#078772] px-6 py-2.5 text-sm font-semibold text-white">Go to Dashboard</button><button type="button" onClick={()=>{setEdit(true);setStep(0)}} className="rounded-md border border-[#078772] bg-white px-6 py-2.5 text-sm font-semibold text-[#078772]">Edit Submission</button></div><p className="mt-3 text-[11px] text-[#8996a6]">Editing updates this month's record and does not create a new submission.</p></section>}
return <form onSubmit={submit} className="space-y-5"><Progress step={step}/>{error&&<ErrorBanner message={error} onClose={()=>setError('')}/>}<section className="overflow-hidden rounded-xl border border-[#dbe3ec] bg-white shadow-[0_8px_24px_rgba(18,42,68,.04)]"><div className="border-b border-[#e7edf3] px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-[#eaf9f5] text-xl text-[#078772]">{['⌂','✓','★','◉','✓'][step]}</div><div className="min-w-0"><h3 className="text-[16px] font-bold text-[#11213a]">{step+1}. {steps[step]}</h3><p className="mt-0.5 text-[11px] leading-4 text-[#64748b]">{['Let us know about your current financial and family situation.','Tell us how we can support you at this time.','Your feedback helps us improve our services.','Do you know anyone who might benefit from our services?','Please review your details before submitting.'][step]}</p></div></div></div><div className="p-5 sm:p-6">
{step===0&&<div className="space-y-5"><div className="grid min-w-0 gap-4 md:grid-cols-2"><SelectField label="Overall Family Status" value={f.overallFamilyStatus} onChange={v=>set('overallFamilyStatus',v)} options={OVERALL_FAMILY_STATUS} error={fieldErrors.overallFamilyStatus}/><SelectField label="Financial Comfort" value={f.financialComfort} onChange={v=>set('financialComfort',v)} options={FINANCIAL_COMFORT} error={fieldErrors.financialComfort}/></div><div className="min-w-0"><p className="mb-2 text-[13px] font-semibold text-[#14223a]">Major Changes <span className="font-normal text-[#66758b]">(Select all that apply)</span></p><OptionGrid options={MAJOR_CHANGES} values={f.majorChanges} onToggle={v=>toggle('majorChanges',v)}/></div><label className="block"><span className="mb-2 block text-[13px] font-semibold text-[#14223a]">Other Major Change (if any)</span><textarea value={f.otherMajorChange} onChange={e=>set('otherMajorChange',e.target.value)} maxLength={500} placeholder="Please specify if any other major changes..." className="h-24 w-full resize-none rounded-[7px] border border-[#cfdae6] p-3 text-[12px] text-[#243650] outline-none focus:border-[#079178] focus:ring-2 focus:ring-teal-50"/><div className="mt-1 text-right text-[10px] text-[#738297]">{f.otherMajorChange.length}/500</div></label></div>}
{step===1&&<div className="space-y-2">{supportOptions.map(v=>{const on=f.assistanceRequired.includes(v);return <button type="button" key={v} onClick={()=>toggle('assistanceRequired',v)} className={cx("flex w-full items-center gap-3 rounded-[6px] border px-4 py-3 text-left text-[12px] transition",on?"border-[#079178] bg-[#effaf7] text-[#075f53]":"border-[#d9e2ec] bg-white text-[#263852] hover:border-[#aebdcd]")}><span className={cx("grid h-[18px] w-[18px] shrink-0 place-items-center rounded-[4px] border text-[11px]",on?"border-[#079178] bg-[#079178] text-white":"border-[#cbd5e1]")}>{on?'✓':''}</span>{v}</button>})}{fieldErrors.assistanceRequired&&<p className="pt-1 text-[11px] text-red-500">{fieldErrors.assistanceRequired}</p>}</div>}
{step===2&&<div className="space-y-5"><div><p className="mb-2 text-[13px] font-semibold text-[#14223a]">How would you rate your overall experience with HappyCoin?</p><div className="flex gap-1">{['1','2','3','4','5'].map(v=><button type="button" key={v} onClick={()=>set('serviceRating',v)} className={cx("text-3xl leading-none",Number(v)<=Number(f.serviceRating||0)?"text-[#f3b82d]":"text-[#cbd5e1]")}>★</button>)}</div>{fieldErrors.serviceRating&&<p className="mt-1 text-[11px] text-red-500">{fieldErrors.serviceRating}</p>}</div><label className="block"><span className="mb-2 block text-[13px] font-semibold text-[#14223a]">What did you like the most?</span><textarea value={f.suggestions} onChange={e=>set('suggestions',e.target.value)} maxLength={500} placeholder="Share your feedback..." className="h-28 w-full resize-none rounded-[7px] border border-[#cfdae6] p-3 text-[12px] outline-none focus:border-[#079178] focus:ring-2 focus:ring-teal-50"/><div className="mt-1 text-right text-[10px] text-[#738297]">{f.suggestions.length}/500</div></label></div>}
{step===3&&<div className="space-y-5"><div><p className="mb-3 text-[13px] font-semibold text-[#14223a]">Would you like to refer someone to HappyCoin?</p><div className="flex flex-wrap gap-5 text-[12px] text-[#263852]"><label className="flex items-center gap-2"><input type="radio" name="refer" checked={f.recommendHappyCoin==='Yes'} onChange={()=>{set('recommendHappyCoin','Yes');if(!f.referrals.length)addReferral()}} className="accent-[#079178]"/> Yes, I have a referral</label><label className="flex items-center gap-2"><input type="radio" name="refer" checked={f.recommendHappyCoin==='No'} onChange={()=>set('recommendHappyCoin','No')} className="accent-[#079178]"/> No, not at this time</label></div>{fieldErrors.recommendHappyCoin&&<p className="mt-2 text-[11px] text-red-500">{fieldErrors.recommendHappyCoin}</p>}</div>{f.recommendHappyCoin==='Yes'&&<div className="space-y-3"><div className="overflow-x-auto rounded-lg border border-[#d9e2ec]"><div className="min-w-[650px]"><div className="grid grid-cols-[1.3fr_1fr_1fr_70px] gap-3 bg-[#f7f9fb] px-4 py-2 text-[10px] font-bold uppercase tracking-wide text-[#66758b]"><div>Referral Name</div><div>Relationship</div><div>Mobile Number</div><div></div></div>{f.referrals.map((r,i)=><div key={i} className="grid grid-cols-[1.3fr_1fr_1fr_70px] gap-3 border-t border-[#e6ecf2] px-4 py-3"><div><input value={r.name} onChange={e=>updateReferral(i,'name',e.target.value)} placeholder="Full name" className={cx("h-10 w-full min-w-0 rounded-md border px-3 text-[12px] outline-none",fieldErrors['referrals.'+i+'.name']?"border-red-400":"border-[#cfdae6] focus:border-[#079178]")}/>{fieldErrors['referrals.'+i+'.name']&&<p className="mt-1 text-[10px] text-red-500">{fieldErrors['referrals.'+i+'.name']}</p>}</div><select value={r.relationship} onChange={e=>updateReferral(i,'relationship',e.target.value)} className="h-10 min-w-0 rounded-md border border-[#cfdae6] bg-white px-2 text-[12px]">{relationshipOptions.map(x=><option key={x}>{x}</option>)}</select><div><input value={r.mobile} onChange={e=>updateReferral(i,'mobile',e.target.value)} placeholder="9876543210" className={cx("h-10 w-full min-w-0 rounded-md border px-3 text-[12px] outline-none",fieldErrors['referrals.'+i+'.mobile']?"border-red-400":"border-[#cfdae6] focus:border-[#079178]")}/>{fieldErrors['referrals.'+i+'.mobile']&&<p className="mt-1 text-[10px] text-red-500">{fieldErrors['referrals.'+i+'.mobile']}</p>}</div><button type="button" onClick={()=>removeReferral(i)} className="h-10 rounded-md border border-[#e2e8f0] text-[11px] text-[#b42318]">Remove</button></div>)}</div></div><button type="button" onClick={addReferral} className="rounded-md border border-[#079178] bg-white px-4 py-2 text-[12px] font-semibold text-[#079178]">+ Add Referral</button>{fieldErrors.referrals&&<p className="text-[11px] text-red-500">{fieldErrors.referrals}</p>}</div>}</div>}
{step===4&&<div className="overflow-hidden rounded-lg border border-[#d9e2ec]"><div className="flex items-center justify-between border-b border-[#e6ecf2] bg-[#f8fafc] px-4 py-3"><div className="text-[13px] font-bold text-[#14223a]">Check-in Summary</div><button type="button" onClick={()=>setStep(0)} className="text-[11px] font-semibold text-[#079178]">Edit</button></div>{summary.map((r,i)=><div key={r.k} className={cx("grid grid-cols-[160px_1fr] gap-4 px-4 py-3 text-[12px]",i<summary.length-1&&"border-b border-[#edf1f5]")}><div className="font-medium text-[#627187]">{r.k}</div><div className="break-words font-medium text-[#243650]">{r.v}</div></div>)}</div>}
</div><div className="flex items-center justify-between border-t border-[#e7edf3] px-5 py-4"><button type="button" onClick={back} disabled={step===0} className={cx("rounded-[7px] border px-6 py-2.5 text-[12px] font-semibold",step===0?"cursor-not-allowed border-[#d7e0e8] text-[#a5b2c0]":"border-[#078772] text-[#17324f] hover:bg-[#f4fbf9]")}>← &nbsp;Back</button>{step<4?<button type="button" onClick={next} className="rounded-[7px] bg-[#078772] px-7 py-2.5 text-[12px] font-semibold text-white shadow-sm hover:bg-[#066f60]">Next &nbsp;→</button>:<button type="submit" disabled={saving} className="rounded-[7px] bg-[#078772] px-7 py-2.5 text-[12px] font-semibold text-white shadow-sm disabled:opacity-60">{saving?'Saving…':'Submit Check-in'}</button>}</div></section></form>}
`);

write('src/app/dashboard/page.tsx',String.raw`"use client";
import {useEffect,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
import CheckinForm from "@/components/CheckinForm";

type Customer=Record<string,any>;
const cx=(...v:Array<string|false|undefined>)=>v.filter(Boolean).join(" ");
const nav=[['dashboard','▦','Dashboard'],['checkin','▣','Client Check-in'],['profile','○','My Profile'],['documents','□','Documents'],['resources','◇','Education & Resources'],['support','?','Support']];
function Brand(){return <div className="flex items-center gap-3 px-5"><img src="/happycoin-mark.svg" alt="Happycoin" className="h-12 w-12"/><div><div className="text-[19px] font-bold leading-5 text-[#10203a]">Happycoin</div><div className="mt-1 text-[11px] text-[#536a86]">Wealthier Tomorrows</div></div></div>}
function Topbar({name}:{name:string}){const initials=name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();return <header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-[#e6edf3] bg-white px-5 md:px-7"><div className="relative w-full max-w-[560px]"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-[#5d718b]">⌕</span><input aria-label="Search" placeholder="Search anything..." className="h-10 w-full rounded-[8px] border border-[#d7e0e8] bg-white pl-10 pr-4 text-[13px] text-[#34455e] outline-none focus:border-[#9bcfc5]"/></div><div className="ml-5 flex shrink-0 items-center gap-4"><div className="relative hidden sm:block"><span className="text-xl text-[#1e3553]">♧</span><span className="absolute -right-1 -top-1 grid h-4 w-4 place-items-center rounded-full bg-[#e82727] text-[9px] text-white">3</span></div><div className="grid h-10 w-10 place-items-center rounded-full bg-[#087f70] text-xs font-bold text-white">{initials}</div><div className="hidden md:block"><div className="max-w-[160px] truncate text-[12px] font-bold text-[#10203a]">{name}</div></div><span className="hidden text-[#42546b] md:block">⌄</span></div></header>}
function Sidebar({view,setView}:{view:string;setView:(v:string)=>void}){return <aside className="fixed inset-y-0 left-0 z-40 hidden w-[270px] flex-col border-r border-[#e3eaf1] bg-white py-5 xl:flex"><Brand/><nav className="mt-8 space-y-1 px-3">{nav.map(([id,icon,label])=><button key={id} onClick={()=>setView(id)} className={cx("relative flex w-full items-center gap-3 rounded-[8px] px-4 py-3 text-left text-[13px] font-medium transition",view===id?"bg-[#edf9f6] text-[#076e61]":"text-[#31445f] hover:bg-[#f7f9fb]")}>{view===id&&<span className="absolute bottom-1 left-0 top-1 w-[3px] rounded-full bg-[#079178]"/>}<span className="w-5 text-center text-[17px]">{icon}</span><span>{label}</span></button>)}</nav><div className="mt-auto px-5"><div className="rounded-xl bg-[#effaf8] p-4"><div className="text-[12px] font-bold text-[#13243e]">Your journey continues.</div><p className="mt-2 text-[11px] leading-5 text-[#526781]">A wealthier tomorrow starts with staying connected to your plan.</p></div><div className="mt-5 text-[10px] leading-5 text-[#8a99ac]">© 2026 HappyCoin<br/>All rights reserved.<br/><span className="mt-2 inline-block">v1.0.0</span></div></div></aside>}
function RightRail({c}:{c:Customer}){const now=new Date();const next=new Date(now.getFullYear(),now.getMonth()+1,1);const nextLabel=next.toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'});const rm=c.relationshipManager||c.owner||c.Owner||{};const rmName=rm.name||rm.fullName||rm.Name||c.ownerName||'Relationship Manager';const rmMobile=rm.mobile||rm.phone||rm.Mobile||c.rmMobile||'';const rmEmail=rm.email||rm.Email||c.rmEmail||'';return <div className="space-y-4"><section className="overflow-hidden rounded-xl bg-gradient-to-br from-[#0b756d] to-[#058f82] px-5 py-5 text-white shadow-sm"><div className="text-[12px] text-white/80">Next Check-in</div><div className="mt-1 text-[22px] font-bold tracking-tight">{nextLabel}</div><div className="mt-1 text-[12px] text-white/90">10:00 AM IST</div></section><section className="rounded-xl border border-[#dce4ec] bg-white p-5 shadow-[0_4px_14px_rgba(26,52,83,.03)]"><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#fff8df] text-lg">💡</div><div><div className="text-[14px] font-bold text-[#12233d]">Why this matters?</div><p className="mt-2 text-[12px] leading-5 text-[#63758c]">Your regular check-in helps us understand your needs better and give you timely advice, so you can stay on track towards your goals.</p></div></div></section><section className="rounded-xl border border-[#bfece3] bg-[#f0fbf8] p-5"><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white text-lg">☎</div><div className="min-w-0 flex-1"><div className="text-[14px] font-bold text-[#12233d]">Need Assistance?</div><div className="text-[12px] text-[#63758c]">We are here to help you.</div><div className="mt-4 rounded-lg bg-white p-4"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#c9efe8] text-[12px] font-bold text-[#08796b]">RM</div><div className="min-w-0"><div className="break-words text-[13px] font-bold text-[#12233d]">{rmName}</div><div className="text-[10px] text-[#728196]">Relationship Manager</div>{rmMobile&&<div className="mt-2 break-all text-[11px] text-[#243650]">☎ {rmMobile}</div>}{rmEmail&&<div className="mt-1 break-all text-[11px] text-[#243650]">✉ {rmEmail}</div>}{rmMobile&&<a href={'https://wa.me/91'+String(rmMobile).replace(/\D/g,'').slice(-10)} target="_blank" className="mt-3 inline-flex rounded-md border border-[#079178] px-3 py-2 text-[10px] font-bold text-[#079178]">Chat on WhatsApp</a>}</div></div></div><div className="my-3 h-px bg-[#d9e6e2]"/><div className="rounded-lg bg-white p-4"><div className="text-[13px] font-bold text-[#12233d]">Customer Care</div><div className="text-[10px] text-[#728196]">HappyCoin Support Team</div><div className="mt-2 text-[11px] text-[#8794a6]">Contact details will be added once provided.</div></div></div></div></section></div>}
function Home({name}:{name:string}){const today=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());return <div><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight text-[#10203a]">Good Morning, {name} 👋</h1><p className="mt-1 text-[12px] text-[#64758c]">Let’s build a better financial future together.</p></div><div className="rounded-md border border-[#e2e8ef] bg-white px-4 py-2 text-[10px] text-[#53657b]">{today}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl bg-[#edf9f6] p-4"><div className="text-[11px] text-[#5c6e84]">Check-ins Completed</div><div className="mt-2 text-2xl font-bold text-[#10203a]">12</div></div><div className="rounded-xl bg-[#fff7e8] p-4"><div className="text-[11px] text-[#5c6e84]">Pending Actions</div><div className="mt-2 text-2xl font-bold text-[#10203a]">2</div></div><div className="rounded-xl bg-[#eef6ff] p-4"><div className="text-[11px] text-[#5c6e84]">Upcoming Reviews</div><div className="mt-2 text-2xl font-bold text-[#10203a]">3</div></div><div className="rounded-xl bg-[#f4efff] p-4"><div className="text-[11px] text-[#5c6e84]">Resources Available</div><div className="mt-2 text-2xl font-bold text-[#10203a]">5</div></div></div><section className="mt-5 overflow-hidden rounded-xl bg-gradient-to-r from-[#153652] via-[#224a63] to-[#1d604f] p-8 text-white"><div className="text-[10px] font-semibold uppercase tracking-[.2em] text-white/70">Our Mission</div><div className="mt-2 text-3xl font-bold">Wealthier Tomorrows</div><div className="mt-2 text-[12px] text-white/85">Better conversations. Brighter decisions. A more secure you.</div><div className="mt-8 text-right text-[12px] italic text-white/80">“A small step today creates a stronger tomorrow.”</div></section></div>}
function Placeholder({title}:{title:string}){return <div className="rounded-xl border border-[#dce4ec] bg-white p-8"><h2 className="text-xl font-bold text-[#10203a]">{title}</h2><p className="mt-2 text-sm text-[#6b7b90]">This section will be added next without changing the approved portal layout.</p></div>}
export default function Dashboard(){const sp=useSearchParams();const [c,setC]=useState<Customer|null>(null);const [view,setView]=useState(sp.get('view')==='checkin'?'checkin':'dashboard');useEffect(()=>{fetch('/api/customer',{cache:'no-store'}).then(async r=>{if(r.status===401){location.href='/';return null}return r.ok?r.json():null}).then(j=>j&&setC(j.customer??j))},[]);useEffect(()=>{const h=(e:any)=>setView(e.detail||'dashboard');window.addEventListener('happycoin:view',h);return()=>window.removeEventListener('happycoin:view',h)},[]);const name=useMemo(()=>{if(!c)return 'HappyCoin Client';return [c.firstName,c.lastName].filter(Boolean).join(' ')||c.fullName||'HappyCoin Client'},[c]);if(!c)return <div className="min-h-screen bg-[#f7f9fc] p-8 text-sm text-[#6b7b90]">Loading HappyCoin portal…</div>;return <div className="min-h-screen bg-[#f7f9fc] text-[#10203a]"><Sidebar view={view} setView={setView}/><div className="min-h-screen xl:ml-[270px]"><Topbar name={name}/><main className="mx-auto w-full max-w-[1500px] px-4 py-7 sm:px-6 lg:px-8">{view==='dashboard'&&<Home name={name}/>} {view==='checkin'&&<><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-[29px] font-bold tracking-tight text-[#10203a]">Monthly Client Care Check-in</h1><p className="mt-1 text-[14px] text-[#61738a]">Help us understand your current situation so we can support you better.</p></div><div className="pt-2 text-[14px] font-medium text-[#4f627c]">{new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date())}</div></div><div className="grid min-w-0 gap-6 2xl:grid-cols-[minmax(0,1fr)_340px] xl:grid-cols-[minmax(0,1fr)_320px]"><div className="min-w-0"><CheckinForm/></div><div className="min-w-0"><RightRail c={c}/></div></div></>} {view==='profile'&&<Placeholder title="My Profile"/>}{view==='documents'&&<Placeholder title="Documents"/>}{view==='resources'&&<Placeholder title="Education & Resources"/>}{view==='support'&&<Placeholder title="Help & Support"/>}</main></div></div>}
`);

console.log('Applied exact HappyCoin reference UI rebuild');
