const fs=require('fs');
const p='src/lib/field-mapping.ts';
let s=fs.readFileSync(p,'utf8');
s=s.replace('  referrals: Array<{ name: string; mobile: string }>;','  referrals?: Array<{ name: string; mobile: string }>;');
s=s.replaceAll('input.referrals.length','(input.referrals ?? []).length');
s=s.replaceAll('input.referrals.map(','(input.referrals ?? []).map(');
fs.writeFileSync(p,s);
const route='src/app/api/checkin/submit/route.ts';
let r=fs.readFileSync(route,'utf8');
r=r.replaceAll('event:"CHECKIN_UPDATED"','event:"CHECKIN_CREATED"');
r=r.replaceAll('event:"CHECKIN_SAVE_FAILED"','event:"CHECKIN_CREATE_FAILED"');
fs.writeFileSync(route,r);
console.log('Applied referral and logger compatibility fixes');